remote_theme: pmarsceill/just-the-docs #jekyll-theme-minimal
#theme: just-the-docs
title: ParsePort XBRL Service
locale: en_US
logo: images/logo.png

owner:
  name: ParsePort Aps
  email: support@parseport.com
  linkedin: parseport-aps

markdown: kramdown

show_downloads: false
permalink: pretty
# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019 ParsePort."
site-footer: "Copyright &copy; 2019 ParsePort."

# Aux links for the upper right navigation
aux_links:
  "ParsePort.com":
    - "//parseport.com/"
